import asyncio
import logging
import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict

from app.services.documentation.comprehensive import ComprehensiveDocBuilder

logger = logging.getLogger(__name__)


def _mask_token(token: str) -> str:
    if not token or len(token) < 6:
        return "***"
    return f"{token[:3]}…{token[-3:]}"


@dataclass
class GenerationResult:
    """Result of the manual documentation generation."""

    workspace: Path
    docs_dir: Path
    summary: str
    architecture: str
    workflow: str
    api_doc: str

    def cleanup(self) -> None:
        """Remove the temporary workspace."""
        shutil.rmtree(self.workspace, ignore_errors=True)


class ManualDocGenerator:
    """Generate documentation artefacts for a repository using LLM rotation."""

    def __init__(self, doc_persona: str = "internal") -> None:
        self.doc_persona = doc_persona

    async def generate(self, repo_full_name: str, github_token: str) -> GenerationResult:
        """Clone repository, generate docs, and return generation artefacts."""
        workspace = Path(tempfile.mkdtemp(prefix="docai_manual_"))
        logger.info("📥 Cloning %s for manual generation", repo_full_name)

        try:
            await self._clone_repository(repo_full_name, github_token, workspace)
            docs_dir = workspace / "docs"
            self._prepare_docs_directory(docs_dir)

            builder = ComprehensiveDocBuilder(workspace, doc_persona=self.doc_persona)
            generated_docs: Dict[str, str] = await builder.build()

            summary = generated_docs.get("summary", "")
            architecture = generated_docs.get("architecture", "")
            workflow = generated_docs.get("workflow", "")
            api_doc = generated_docs.get("api", "")

            # Create the proper folder structure based on doc_persona
            # Map 'dev' to 'developer' for folder naming
            persona_folder_name = "dev" if self.doc_persona == "dev" else "internal"
            print(f"📚 Creating documentation in {persona_folder_name} folder")
            
            # Create the current persona folder
            persona_dir = docs_dir / persona_folder_name
            persona_dir.mkdir(exist_ok=True)
            
            # Create the other persona folder if it doesn't exist
            # But don't modify its contents if it already exists
            other_persona = "internal" if persona_folder_name == "dev" else "dev"
            other_persona_dir = docs_dir / other_persona
            other_persona_dir.mkdir(exist_ok=True)
            
            # Only add a placeholder README if the other persona folder is empty
            if not any(other_persona_dir.iterdir()):
                print(f"📝 Creating placeholder README in {other_persona} folder")
                self._write_text(other_persona_dir / "README.md", f"# Documentation for {other_persona}\n\nThis persona documentation is not available.")
            
            # Persist artefacts in the correct persona folder
            self._write_text(persona_dir / "SUMMARY.md", summary)
            
            # Create architecture folder inside the persona folder
            architecture_dir = persona_dir / "architecture"
            architecture_dir.mkdir(exist_ok=True)
            self._write_text(architecture_dir / "v1.0-architecture.md", architecture)
            self._write_text(architecture_dir / "current.md", architecture)

            # Create workflow folder inside the persona folder
            workflow_dir = persona_dir / "workflow"
            workflow_dir.mkdir(exist_ok=True)
            self._write_text(workflow_dir / "v1.0-workflow.md", workflow)
            self._write_text(workflow_dir / "current.md", workflow)

            # Add API doc inside the persona folder
            self._write_text(persona_dir / "api.md", api_doc)
            
            # Create changes folder inside the persona folder
            (persona_dir / "changes").mkdir(exist_ok=True)

            # Update root README & changelog for traceability
            self._write_text(workspace / "README.md", summary)
            changelog = (
                "# Changelog\n\n"
                "## [1.0.0] - Auto-generated documentation\n\n"
                "### Added\n"
                "- Comprehensive documentation set generated by DocIt AI\n"
                "- Architecture, workflow, API docs under /docs\n"
                "- Updated README summary\n"
            )
            self._write_text(workspace / "CHANGELOG.md", changelog)

            return GenerationResult(
                workspace=workspace,
                docs_dir=docs_dir,
                summary=summary,
                architecture=architecture,
                workflow=workflow,
                api_doc=api_doc,
            )
        except Exception:
            logger.exception("Manual documentation generation failed for %s", repo_full_name)
            shutil.rmtree(workspace, ignore_errors=True)
            raise

    async def _clone_repository(self, repo_full_name: str, token: str, workspace: Path) -> None:
        if not token:
            raise ValueError("GitHub token is required to clone the repository")

        env = os.environ.copy()
        env["GIT_TERMINAL_PROMPT"] = "0"
        url = f"https://x-access-token:{token}@github.com/{repo_full_name}.git"
        masked = url.replace(token, _mask_token(token))
        logger.info("RUN git clone %s", masked)

        def _clone() -> None:
            subprocess.run(
                ["git", "clone", "--depth", "1", url, str(workspace)],
                check=True,
                env=env,
            )

        await asyncio.to_thread(_clone)

    def _prepare_docs_directory(self, docs_dir: Path) -> None:
        docs_dir.mkdir(exist_ok=True)

    def _write_text(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
