"""
Documentation Planner - Phase 1/3: Metadata-only planning layer with semantic signals

This module introduces a planning layer that determines which documentation sections
should exist for a given repository, WITHOUT changing the generation mechanism.

Current Phase 1/3 Behavior:
- Analyzes repository structure
- Accepts optional SemanticSnapshot from Phase 3 extractors
- Produces structured plan with section metadata
- Plan is used to build prompts but NOT for per-section generation
- Single LLM call still generates all content
- Output format remains unchanged (4 markdown sections)

Future Phases:
- Phase 4: Use plan for section-level generation
- Phase 5: User customization of plan
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional, Set
from pathlib import Path
import re


@dataclass
class SectionPlan:
    """
    Metadata for a single documentation section.

    In Phase 1, this is informational only - used for prompt building,
    not for actual section-level generation.
    """
    id: str  # Unique identifier (e.g., "overview", "auth-flow")
    title: str  # Human-readable title
    type: Literal["summary", "architecture", "workflow", "api", "custom"]
    # File patterns this section depends on
    dependencies: List[str] = field(default_factory=list)
    priority: int = 5  # 1-10, higher = more important
    required: bool = True  # If False, section is optional based on heuristics


@dataclass
class DocumentationPlan:
    """
    Complete plan for documentation generation.

    Contains metadata about what sections should exist and their relationships.
    Does NOT contain actual content - that's still generated by the LLM.
    """
    sections: List[SectionPlan] = field(default_factory=list)
    # Detected repo type (web-api, cli-tool, library, etc.)
    repo_type: str = "generic"
    complexity_score: int = 5  # 1-10 estimated complexity
    # Phase 3: Semantic snapshot used for planning
    semantic_signals: Dict[str, Any] = field(default_factory=dict)

    def get_sections_by_type(self, section_type: str) -> List[SectionPlan]:
        """Get all sections of a specific type."""
        return [s for s in self.sections if s.type == section_type]

    def get_required_sections(self) -> List[SectionPlan]:
        """Get sections that must be included."""
        return [s for s in self.sections if s.required]


class DocumentationPlanner:
    """
    Plans documentation structure based on repository analysis.

    Phase 1: Simple heuristic-based planning
    - Uses file patterns and keywords
    - No AST parsing (future phase)
    - Deterministic output
    - Graceful fallback to defaults
    """

    # File patterns that indicate specific section needs
    SECTION_HEURISTICS = {
        "auth": {
            "patterns": [
                r"auth", r"login", r"oauth", r"jwt", r"session", r"password",
                r"middleware.*auth", r"guard", r"permission", r"role"
            ],
            "section_id": "authentication-flow",
            "section_title": "Authentication & Authorization",
            "section_type": "architecture",
            "priority": 8,
        },
        "deployment": {
            "patterns": [
                r"docker", r"dockerfile", r"k8s", r"kubernetes", r"helm",
                r"terraform", r"pulumi", r"\.github/workflows", r"deploy",
                r"ecs", r"gke", r"aks", r"serverless"
            ],
            "section_id": "deployment-architecture",
            "section_title": "Deployment & Infrastructure",
            "section_type": "architecture",
            "priority": 7,
        },
        "database": {
            "patterns": [
                r"database", r"db", r"migration", r"schema", r"model",
                r"entity", r"repository", r"sql", r"postgres", r"mongo",
                r"redis", r"prisma", r"sqlalchemy", r"typeorm"
            ],
            "section_id": "data-layer",
            "section_title": "Data Layer & Storage",
            "section_type": "architecture",
            "priority": 7,
        },
        "api": {
            "patterns": [
                r"api", r"route", r"endpoint", r"controller", r"handler",
                r"graphql", r"rest", r"swagger", r"openapi", r"fastapi",
                r"express", r"flask", r"django"
            ],
            "section_id": "api-reference",
            "section_title": "API Reference",
            "section_type": "api",
            "priority": 9,
        },
        "frontend": {
            "patterns": [
                r"react", r"vue", r"angular", r"svelte", r"nextjs", r"nuxt",
                r"component", r"frontend", r"client", r"ui", r"css", r"scss",
                r"tailwind", r"styled-components"
            ],
            "section_id": "frontend-architecture",
            "section_title": "Frontend Architecture",
            "section_type": "architecture",
            "priority": 6,
        },
        "testing": {
            "patterns": [
                r"test", r"spec", r"jest", r"pytest", r"mocha", r"cypress",
                r"playwright", r"unit", r"integration", r"e2e"
            ],
            "section_id": "testing-strategy",
            "section_title": "Testing Strategy",
            "section_type": "workflow",
            "priority": 5,
        },
        "ci_cd": {
            "patterns": [
                r"\.github/workflows", r"\.gitlab-ci", r"jenkins", r"circleci",
                r"travis", r"buildkite", r"ci", r"cd", r"pipeline"
            ],
            "section_id": "ci-cd-pipeline",
            "section_title": "CI/CD Pipeline",
            "section_type": "workflow",
            "priority": 6,
        },
    }

    def __init__(self):
        """Initialize planner with default configuration."""
        self._fallback_plan = self._create_fallback_plan()

    def create_plan(
        self,
        repo_analysis: Dict,
        semantic_snapshot: Optional[Dict[str, Any]] = None,
    ) -> DocumentationPlan:
        """
        Create documentation plan from repository analysis.

        Phase 3: Accepts optional semantic_snapshot for improved planning.

        Args:
            repo_analysis: Dictionary containing repo metadata
                - project_name: str
                - file_count: int
                - languages: List[str]
                - main_directories: List[str]
                - dependencies: Dict
                - frameworks: List[str]
                - database_tech: List[str]
                - deployment_tech: List[str]
            semantic_snapshot: Optional semantic signals from Phase 3 extractors

        Returns:
            DocumentationPlan with section metadata

        Raises:
            Never raises - always returns a valid plan (fallback on error)
        """
        try:
            if not repo_analysis or not isinstance(repo_analysis, dict):
                return self._fallback_plan

            sections = []
            detected_features = self._detect_features(repo_analysis)

            # Phase 3: Enhance with semantic signals if available
            if semantic_snapshot:
                self._enhance_with_semantic_signals(
                    detected_features, semantic_snapshot)

            # Always include core sections (required)
            sections.extend(self._create_core_sections())

            # Add conditional sections based on heuristics
            for feature, detected in detected_features.items():
                if detected and feature in self.SECTION_HEURISTICS:
                    heuristic = self.SECTION_HEURISTICS[feature]
                    section = SectionPlan(
                        id=heuristic["section_id"],
                        title=heuristic["section_title"],
                        type=heuristic["section_type"],
                        dependencies=heuristic["patterns"],
                        priority=heuristic["priority"],
                        required=False,  # These are conditional
                    )
                    sections.append(section)

            # Sort by priority (highest first)
            sections.sort(key=lambda s: s.priority, reverse=True)

            # Detect repo type for metadata
            repo_type = self._detect_repo_type(
                repo_analysis, detected_features)
            complexity = self._estimate_complexity(repo_analysis)

            return DocumentationPlan(
                sections=sections,
                repo_type=repo_type,
                complexity_score=complexity,
                semantic_signals=semantic_snapshot or {},  # Phase 3
            )

        except Exception as e:
            # NEVER fail - always return fallback plan
            print(f"⚠️ Planner error, using fallback: {e}")
            return self._fallback_plan

    def _enhance_with_semantic_signals(
        self,
        detected_features: Dict[str, bool],
        semantic_snapshot: Dict[str, Any],
    ) -> None:
        """
        Enhance feature detection with Phase 3 semantic signals.

        Modifies detected_features in place.
        """
        try:
            # API detection
            if semantic_snapshot.get("primary_framework") in ["fastapi", "express", "django", "flask"]:
                detected_features["api"] = True

            if semantic_snapshot.get("detected_routes"):
                detected_features["api"] = True

            # Auth detection
            if semantic_snapshot.get("auth_patterns"):
                detected_features["auth"] = True

            # Database detection
            if semantic_snapshot.get("data_layer") or semantic_snapshot.get("database_type"):
                detected_features["database"] = True

            # Infra detection
            if semantic_snapshot.get("infra_features"):
                detected_features["deployment"] = True
                detected_features["ci_cd"] = True

        except Exception as e:
            # Non-fatal - just log
            print(f"⚠️ Semantic signal enhancement failed: {e}")

    def _detect_features(self, repo_analysis: Dict) -> Dict[str, bool]:
        """
        Detect which features exist in the repository.

        Uses simple pattern matching on file paths and analysis data.
        """
        features = {key: False for key in self.SECTION_HEURISTICS.keys()}

        # Combine all text to search
        search_text = ""

        # Add directories
        dirs = repo_analysis.get("main_directories", [])
        search_text += " " + " ".join(dirs)

        # Add languages
        languages = repo_analysis.get("languages", [])
        search_text += " " + " ".join(languages)

        # Add frameworks
        frameworks = repo_analysis.get("frameworks", [])
        search_text += " " + " ".join(frameworks)

        # Add database tech
        db_tech = repo_analysis.get("database_tech", [])
        search_text += " " + " ".join(db_tech)

        # Add deployment tech
        deploy_tech = repo_analysis.get("deployment_tech", [])
        search_text += " " + " ".join(deploy_tech)

        # Add dependencies keys
        deps = repo_analysis.get("dependencies", {})
        if isinstance(deps, dict):
            search_text += " " + " ".join(deps.keys())

        search_text = search_text.lower()

        # Check each heuristic
        for feature, heuristic in self.SECTION_HEURISTICS.items():
            for pattern in heuristic["patterns"]:
                if re.search(pattern, search_text):
                    features[feature] = True
                    break

        return features

    def _create_core_sections(self) -> List[SectionPlan]:
        """
        Create the 4 required core sections.

        These match the current hardcoded structure and are ALWAYS included.
        """
        return [
            SectionPlan(
                id="overview",
                title="Project Overview",
                type="summary",
                dependencies=["README", "package.json",
                              "pyproject.toml", "Cargo.toml"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="architecture",
                title="System Architecture",
                type="architecture",
                dependencies=["src/", "app/", "lib/", "core/"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="workflow",
                title="Development Workflow",
                type="workflow",
                dependencies=[".github/", "Makefile", "scripts/"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="api",
                title="API Documentation",
                type="api",
                dependencies=["api/", "routes/", "controllers/", "endpoints/"],
                priority=10,
                required=True,
            ),
        ]

    def _create_fallback_plan(self) -> DocumentationPlan:
        """
        Create fallback plan with just the 4 core sections.

        This ensures we NEVER break existing behavior.
        """
        return DocumentationPlan(
            sections=self._create_core_sections(),
            repo_type="generic",
            complexity_score=5,
        )

    def _detect_repo_type(self, repo_analysis: Dict, features: Dict[str, bool]) -> str:
        """Detect the type of repository for metadata purposes."""
        frameworks = repo_analysis.get("frameworks", [])
        languages = repo_analysis.get("languages", [])

        # Web API detection
        if features.get("api") and ("fastapi" in frameworks or "express" in frameworks or "django" in frameworks):
            return "web-api"

        # Frontend detection
        if features.get("frontend") or "react" in frameworks or "vue" in frameworks:
            return "frontend-app"

        # CLI tool detection
        if "cli" in str(frameworks).lower() or "command" in str(repo_analysis.get("main_directories", [])).lower():
            return "cli-tool"

        # Library detection
        if repo_analysis.get("file_count", 0) < 20 and not features.get("deployment"):
            return "library"

        return "generic"

    def _estimate_complexity(self, repo_analysis: Dict) -> int:
        """Estimate repository complexity (1-10) for metadata."""
        score = 5  # Default medium complexity

        # File count factor
        file_count = repo_analysis.get("file_count", 0)
        if file_count > 500:
            score += 2
        elif file_count > 100:
            score += 1
        elif file_count < 10:
            score -= 2

        # Language diversity
        languages = repo_analysis.get("languages", [])
        if len(languages) > 3:
            score += 1

        # Framework complexity
        frameworks = repo_analysis.get("frameworks", [])
        if len(frameworks) > 2:
            score += 1

        # Clamp to 1-10
        return max(1, min(10, score))


# Singleton instance for reuse
_planner_instance: Optional[DocumentationPlanner] = None


def get_planner() -> DocumentationPlanner:
    """Get singleton instance of DocumentationPlanner."""
    global _planner_instance
    if _planner_instance is None:
        _planner_instance = DocumentationPlanner()
    return _planner_instance
