"""
Documentation Planner - Phase 1/3: Metadata-only planning layer with semantic signals

This module introduces a planning layer that determines which documentation sections
should exist for a given repository, WITHOUT changing the generation mechanism.

Current Phase 1/3 Behavior:
- Analyzes repository structure
- Accepts optional SemanticSnapshot from Phase 3 extractors
- Produces structured plan with section metadata
- Plan is used to build prompts but NOT for per-section generation
- Single LLM call still generates all content
- Output format remains unchanged (4 markdown sections)

Future Phases:
- Phase 4: Use plan for section-level generation
- Phase 5: User customization of plan
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional, Set
from pathlib import Path
import re


@dataclass
class SectionPlan:
    """
    Metadata for a single documentation section.

    Dynamic sections based on actual codebase content.
    """
    id: str  # Unique identifier (e.g., "overview", "auth-flow")
    title: str  # Human-readable title
    type: Literal["summary", "architecture", "workflow", "api",
                  "custom", "features", "components", "deployment"]
    # File patterns this section depends on
    dependencies: List[str] = field(default_factory=list)
    priority: int = 5  # 1-10, higher = more important
    required: bool = True  # If False, section is optional based on heuristics
    # What this section should cover
    description: str = ""  # Guidance for content generation


@dataclass
class DocumentationPlan:
    """
    Complete plan for documentation generation.

    Contains metadata about what sections should exist and their relationships.
    Does NOT contain actual content - that's still generated by the LLM.
    """
    sections: List[SectionPlan] = field(default_factory=list)
    # Detected repo type (web-api, cli-tool, library, etc.)
    repo_type: str = "generic"
    complexity_score: int = 5  # 1-10 estimated complexity
    # Phase 3: Semantic snapshot used for planning
    semantic_signals: Dict[str, Any] = field(default_factory=dict)

    def get_sections_by_type(self, section_type: str) -> List[SectionPlan]:
        """Get all sections of a specific type."""
        return [s for s in self.sections if s.type == section_type]

    def get_required_sections(self) -> List[SectionPlan]:
        """Get sections that must be included."""
        return [s for s in self.sections if s.required]

    def to_dict(self) -> Dict[str, Any]:
        """Convert plan to dictionary for serialization."""
        return {
            "repo_type": self.repo_type,
            "complexity_score": self.complexity_score,
            "semantic_signals": self.semantic_signals,
            "sections": [
                {
                    "id": s.id,
                    "title": s.title,
                    "type": s.type,
                    "priority": s.priority,
                    "required": s.required,
                }
                for s in self.sections
            ],
        }


class DocumentationPlanner:
    """
    Plans documentation structure based on repository analysis.

    Phase 1: Simple heuristic-based planning
    - Uses file patterns and keywords
    - No AST parsing (future phase)
    - Deterministic output
    - Graceful fallback to defaults
    """

    # File patterns that indicate specific section needs
    SECTION_HEURISTICS = {
        "auth": {
            "patterns": [
                r"auth", r"login", r"oauth", r"jwt", r"session", r"password",
                r"middleware.*auth", r"guard", r"permission", r"role"
            ],
            "section_id": "authentication-flow",
            "section_title": "Authentication & Authorization",
            "section_type": "architecture",
            "priority": 8,
        },
        "deployment": {
            "patterns": [
                r"docker", r"dockerfile", r"k8s", r"kubernetes", r"helm",
                r"terraform", r"pulumi", r"\.github/workflows", r"deploy",
                r"ecs", r"gke", r"aks", r"serverless"
            ],
            "section_id": "deployment-architecture",
            "section_title": "Deployment & Infrastructure",
            "section_type": "architecture",
            "priority": 7,
        },
        "database": {
            "patterns": [
                r"database", r"db", r"migration", r"schema", r"model",
                r"entity", r"repository", r"sql", r"postgres", r"mongo",
                r"redis", r"prisma", r"sqlalchemy", r"typeorm"
            ],
            "section_id": "data-layer",
            "section_title": "Data Layer & Storage",
            "section_type": "architecture",
            "priority": 7,
        },
        "api": {
            "patterns": [
                r"api", r"route", r"endpoint", r"controller", r"handler",
                r"graphql", r"rest", r"swagger", r"openapi", r"fastapi",
                r"express", r"flask", r"django"
            ],
            "section_id": "api-reference",
            "section_title": "API Reference",
            "section_type": "api",
            "priority": 9,
        },
        "frontend": {
            "patterns": [
                r"react", r"vue", r"angular", r"svelte", r"nextjs", r"nuxt",
                r"component", r"frontend", r"client", r"ui", r"css", r"scss",
                r"tailwind", r"styled-components"
            ],
            "section_id": "frontend-architecture",
            "section_title": "Frontend Architecture",
            "section_type": "architecture",
            "priority": 6,
        },
        "testing": {
            "patterns": [
                r"test", r"spec", r"jest", r"pytest", r"mocha", r"cypress",
                r"playwright", r"unit", r"integration", r"e2e"
            ],
            "section_id": "testing-strategy",
            "section_title": "Testing Strategy",
            "section_type": "workflow",
            "priority": 5,
        },
        "ci_cd": {
            "patterns": [
                r"\.github/workflows", r"\.gitlab-ci", r"jenkins", r"circleci",
                r"travis", r"buildkite", r"ci", r"cd", r"pipeline"
            ],
            "section_id": "ci-cd-pipeline",
            "section_title": "CI/CD Pipeline",
            "section_type": "workflow",
            "priority": 6,
        },
    }

    def __init__(self):
        """Initialize planner with default configuration."""
        self._fallback_plan = self._create_fallback_plan()

    def create_plan(
        self,
        repo_analysis: Dict,
        semantic_snapshot: Optional[Dict[str, Any]] = None,
    ) -> DocumentationPlan:
        """
        Create documentation plan from repository analysis.

        Phase 3: Accepts optional semantic_snapshot for improved planning.

        Args:
            repo_analysis: Dictionary containing repo metadata
                - project_name: str
                - file_count: int
                - languages: List[str]
                - main_directories: List[str]
                - dependencies: Dict
                - frameworks: List[str]
                - database_tech: List[str]
                - deployment_tech: List[str]
            semantic_snapshot: Optional semantic signals from Phase 3 extractors

        Returns:
            DocumentationPlan with section metadata

        Raises:
            Never raises - always returns a valid plan (fallback on error)
        """
        try:
            if not repo_analysis or not isinstance(repo_analysis, dict):
                return self._fallback_plan

            sections = []
            detected_features = self._detect_features(repo_analysis)

            # Phase 3: Enhance with semantic signals if available
            if semantic_snapshot:
                self._enhance_with_semantic_signals(
                    detected_features, semantic_snapshot)

            # Use frontend-specific sections for frontend projects
            if detected_features.get("frontend"):
                sections.extend(self._create_frontend_sections())
            else:
                # Always include core sections (required)
                sections.extend(self._create_core_sections())

            # Add conditional sections based on heuristics
            for feature, detected in detected_features.items():
                if detected and feature in self.SECTION_HEURISTICS:
                    heuristic = self.SECTION_HEURISTICS[feature]
                    section = SectionPlan(
                        id=heuristic["section_id"],
                        title=heuristic["section_title"],
                        type=heuristic["section_type"],
                        dependencies=heuristic["patterns"],
                        priority=heuristic["priority"],
                        required=False,  # These are conditional
                    )
                    sections.append(section)

            # Sort by priority (highest first)
            sections.sort(key=lambda s: s.priority, reverse=True)

            # Detect repo type for metadata
            repo_type = self._detect_repo_type(
                repo_analysis, detected_features)
            complexity = self._estimate_complexity(repo_analysis)

            return DocumentationPlan(
                sections=sections,
                repo_type=repo_type,
                complexity_score=complexity,
                semantic_signals=semantic_snapshot or {},  # Phase 3
            )

        except Exception as e:
            # NEVER fail - always return fallback plan
            print(f"⚠️ Planner error, using fallback: {e}")
            return self._fallback_plan

    def _enhance_with_semantic_signals(
        self,
        detected_features: Dict[str, bool],
        semantic_snapshot: Dict[str, Any],
    ) -> None:
        """
        Enhance feature detection with Phase 3 semantic signals.

        Modifies detected_features in place.
        """
        try:
            primary_framework = semantic_snapshot.get("primary_framework")

            # API detection (backend frameworks)
            if primary_framework in ["fastapi", "express", "django", "flask"]:
                detected_features["api"] = True

            if semantic_snapshot.get("detected_routes"):
                detected_features["api"] = True

            # Frontend detection (React, Vue, Angular, Next.js)
            if primary_framework in ["react", "vue", "angular", "nextjs"]:
                detected_features["frontend"] = True
                # Frontend projects don't need API docs section
                detected_features["api"] = False

            # Auth detection
            if semantic_snapshot.get("auth_patterns"):
                detected_features["auth"] = True

            # Database detection
            if semantic_snapshot.get("data_layer") or semantic_snapshot.get("database_type"):
                detected_features["database"] = True

            # Infra detection
            if semantic_snapshot.get("infra_features"):
                detected_features["deployment"] = True
                detected_features["ci_cd"] = True

        except Exception as e:
            # Non-fatal - just log
            print(f"⚠️ Semantic signal enhancement failed: {e}")

    def _detect_features(self, repo_analysis: Dict) -> Dict[str, bool]:
        """
        Detect which features exist in the repository.

        Uses simple pattern matching on file paths and analysis data.
        """
        features = {key: False for key in self.SECTION_HEURISTICS.keys()}

        # Combine all text to search
        search_text = ""

        # Add directories
        dirs = repo_analysis.get("main_directories", [])
        search_text += " " + " ".join(dirs)

        # Add languages
        languages = repo_analysis.get("languages", [])
        search_text += " " + " ".join(languages)

        # Add frameworks
        frameworks = repo_analysis.get("frameworks", [])
        search_text += " " + " ".join(frameworks)

        # Add database tech
        db_tech = repo_analysis.get("database_tech", [])
        search_text += " " + " ".join(db_tech)

        # Add deployment tech
        deploy_tech = repo_analysis.get("deployment_tech", [])
        search_text += " " + " ".join(deploy_tech)

        # Add dependencies keys
        deps = repo_analysis.get("dependencies", {})
        if isinstance(deps, dict):
            search_text += " " + " ".join(deps.keys())

        search_text = search_text.lower()

        # Check each heuristic
        for feature, heuristic in self.SECTION_HEURISTICS.items():
            for pattern in heuristic["patterns"]:
                if re.search(pattern, search_text):
                    features[feature] = True
                    break

        return features

    def _create_core_sections(self) -> List[SectionPlan]:
        """
        Create the 4 required core sections.

        These match the current hardcoded structure and are ALWAYS included.
        """
        return [
            SectionPlan(
                id="overview",
                title="Project Overview",
                type="summary",
                dependencies=["README", "package.json",
                              "pyproject.toml", "Cargo.toml"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="architecture",
                title="System Architecture",
                type="architecture",
                dependencies=["src/", "app/", "lib/", "core/", "components/"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="workflow",
                title="Development Workflow",
                type="workflow",
                dependencies=[".github/", "Makefile", "scripts/"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="api",
                title="API Documentation",
                type="api",
                dependencies=["api/", "routes/", "controllers/", "endpoints/"],
                priority=10,
                required=True,
            ),
        ]

    def _create_frontend_sections(self) -> List[SectionPlan]:
        """
        Create sections appropriate for frontend projects.

        Replaces generic API docs with frontend-specific sections.
        """
        return [
            SectionPlan(
                id="overview",
                title="Project Overview",
                type="summary",
                dependencies=["README", "package.json"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="architecture",
                title="Frontend Architecture",
                type="architecture",
                dependencies=["src/", "app/", "components/"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="workflow",
                title="Development Workflow",
                type="workflow",
                dependencies=[".github/", "scripts/"],
                priority=10,
                required=True,
            ),
            SectionPlan(
                id="ui-components",
                title="UI Components & Design",
                type="api",
                dependencies=["components/", "ui/", "styles/"],
                priority=9,
                required=True,
            ),
        ]

    def _create_fallback_plan(self) -> DocumentationPlan:
        """
        Create fallback plan with just the 4 core sections.

        This ensures we NEVER break existing behavior.
        """
        return DocumentationPlan(
            sections=self._create_core_sections(),
            repo_type="generic",
            complexity_score=5,
        )

    def _detect_repo_type(self, repo_analysis: Dict, features: Dict[str, bool]) -> str:
        """Detect the type of repository for metadata purposes."""
        frameworks = repo_analysis.get("frameworks", [])
        languages = repo_analysis.get("languages", [])

        # Web API detection
        if features.get("api") and ("fastapi" in frameworks or "express" in frameworks or "django" in frameworks):
            return "web-api"

        # Frontend detection
        if features.get("frontend") or "react" in frameworks or "vue" in frameworks:
            return "frontend-app"

        # CLI tool detection
        if "cli" in str(frameworks).lower() or "command" in str(repo_analysis.get("main_directories", [])).lower():
            return "cli-tool"

        # Library detection
        if repo_analysis.get("file_count", 0) < 20 and not features.get("deployment"):
            return "library"

        return "generic"

    def _estimate_complexity(self, repo_analysis: Dict) -> int:
        """Estimate repository complexity (1-10) for metadata."""
        score = 5  # Default medium complexity

        # File count factor
        file_count = repo_analysis.get("file_count", 0)
        if file_count > 500:
            score += 2
        elif file_count > 100:
            score += 1
        elif file_count < 10:
            score -= 2

        # Language diversity
        languages = repo_analysis.get("languages", [])
        if len(languages) > 3:
            score += 1

        # Framework complexity
        frameworks = repo_analysis.get("frameworks", [])
        if len(frameworks) > 2:
            score += 1

        # Clamp to 1-10
        return max(1, min(10, score))

    def create_dynamic_plan(
        self,
        repo_analysis: Dict,
        semantic_snapshot: Optional[Dict[str, Any]] = None,
        persona: str = "internal",
    ) -> DocumentationPlan:
        """
        Create a truly dynamic documentation plan based on persona and actual codebase.

        Args:
            repo_analysis: Repository analysis data
            semantic_snapshot: Optional semantic extraction results
            persona: 'internal' (code-focused) or 'dev' (functionality-focused)

        Returns:
            DocumentationPlan with dynamically determined sections
        """
        try:
            if not repo_analysis or not isinstance(repo_analysis, dict):
                return self._fallback_plan

            sections = []
            detected_features = self._detect_features(repo_analysis)

            # Enhance with semantic signals
            if semantic_snapshot:
                self._enhance_with_semantic_signals(
                    detected_features, semantic_snapshot)

            # Get actual repository info
            languages = repo_analysis.get("languages", [])
            frameworks = repo_analysis.get("frameworks", [])
            dependencies = repo_analysis.get("dependencies", {})
            primary_framework = semantic_snapshot.get(
                "primary_framework") if semantic_snapshot else None

            # === DYNAMIC SECTION GENERATION BASED ON PERSONA ===

            if persona == "internal":
                # INTERNAL DOCS: Code-focused for company developers
                sections = self._create_internal_sections(
                    detected_features, primary_framework, languages, dependencies
                )
            else:
                # DEV DOCS: Functionality-focused for external developers
                sections = self._create_dev_sections(
                    detected_features, primary_framework, languages, dependencies
                )

            # Sort by priority
            sections.sort(key=lambda s: s.priority, reverse=True)

            # Detect repo type
            repo_type = self._detect_repo_type(
                repo_analysis, detected_features)
            complexity = self._estimate_complexity(repo_analysis)

            return DocumentationPlan(
                sections=sections,
                repo_type=repo_type,
                complexity_score=complexity,
                semantic_signals=semantic_snapshot or {},
            )

        except Exception as e:
            print(f"⚠️ Dynamic planner error, using fallback: {e}")
            return self._fallback_plan

    def _create_internal_sections(
        self,
        detected_features: Dict[str, bool],
        primary_framework: Optional[str],
        languages: List[str],
        dependencies: Dict,
    ) -> List[SectionPlan]:
        """
        Create sections for INTERNAL persona (code-focused).

        Focus: Architecture, implementation details, code organization
        Audience: Engineers working on the codebase
        """
        sections = []

        # Always start with project overview
        sections.append(SectionPlan(
            id="overview",
            title="Project Overview",
            type="summary",
            description="Project purpose, tech stack, and high-level architecture",
            priority=10,
            required=True,
        ))

        # Code Architecture section
        if detected_features.get("frontend"):
            sections.append(SectionPlan(
                id="architecture",
                title="Component Architecture",
                type="architecture",
                description="Component hierarchy, file organization, state management implementation",
                priority=9,
                required=True,
            ))
        else:
            sections.append(SectionPlan(
                id="architecture",
                title="System Architecture",
                type="architecture",
                description="Module structure, service organization, data flow",
                priority=9,
                required=True,
            ))

        # Development Setup section
        sections.append(SectionPlan(
            id="development",
            title="Development Setup & Workflow",
            type="workflow",
            description="Local setup, build commands, testing, contribution guidelines",
            priority=8,
            required=True,
        ))

        # Key Dependencies section
        if dependencies:
            sections.append(SectionPlan(
                id="dependencies",
                title="Key Dependencies & Libraries",
                type="architecture",
                description="Major libraries used and their purposes",
                priority=7,
                required=False,
            ))

        # Component/Library Documentation (for frontend)
        if detected_features.get("frontend"):
            sections.append(SectionPlan(
                id="components",
                title="Component Library",
                type="components",
                description="Reusable components, props, usage patterns",
                priority=7,
                required=False,
            ))

        # API/Integration section (if applicable)
        if detected_features.get("api") or detected_features.get("database"):
            sections.append(SectionPlan(
                id="api",
                title="API & Data Layer",
                type="api",
                description="API endpoints, data models, integration patterns",
                priority=6,
                required=False,
            ))

        # Deployment section (only if actually configured)
        if detected_features.get("deployment"):
            sections.append(SectionPlan(
                id="deployment",
                title="Deployment Configuration",
                type="deployment",
                description="Deployment setup, environment configuration",
                priority=5,
                required=False,
            ))

        return sections

    def _create_dev_sections(
        self,
        detected_features: Dict[str, bool],
        primary_framework: Optional[str],
        languages: List[str],
        dependencies: Dict,
    ) -> List[SectionPlan]:
        """
        Create sections for DEV persona (functionality-focused).

        Focus: What the product does, features, usage
        Audience: External developers using the product/library
        """
        sections = []

        # Product Overview
        sections.append(SectionPlan(
            id="overview",
            title="Product Overview",
            type="summary",
            description="What this product does, key features, use cases",
            priority=10,
            required=True,
        ))

        # Features & Capabilities
        sections.append(SectionPlan(
            id="features",
            title="Features & Capabilities",
            type="features",
            description="Main features, functionality, what users can do",
            priority=9,
            required=True,
        ))

        # Quick Start Guide
        sections.append(SectionPlan(
            id="quickstart",
            title="Quick Start Guide",
            type="workflow",
            description="Get started quickly, basic usage examples",
            priority=8,
            required=True,
        ))

        # Usage Documentation
        if detected_features.get("frontend"):
            sections.append(SectionPlan(
                id="usage",
                title="Usage & Integration",
                type="api",
                description="How to integrate, configure, and use",
                priority=7,
                required=True,
            ))
        else:
            sections.append(SectionPlan(
                id="api",
                title="API Reference",
                type="api",
                description="API methods, parameters, examples",
                priority=7,
                required=True,
            ))

        # Configuration (if applicable)
        if detected_features.get("deployment") or dependencies:
            sections.append(SectionPlan(
                id="configuration",
                title="Configuration Options",
                type="architecture",
                description="Configuration options, environment variables, customization",
                priority=6,
                required=False,
            ))

        # Examples (always useful for dev docs)
        sections.append(SectionPlan(
            id="examples",
            title="Examples & Tutorials",
            type="workflow",
            description="Common use cases, code examples, best practices",
            priority=5,
            required=False,
        ))

        return sections


# Singleton instance for reuse
_planner_instance: Optional[DocumentationPlanner] = None


def get_planner() -> DocumentationPlanner:
    """Get singleton instance of DocumentationPlanner."""
    global _planner_instance
    if _planner_instance is None:
        _planner_instance = DocumentationPlanner()
    return _planner_instance
