# processor.py
import os, subprocess, tempfile, shutil
from github_app import get_installation_token
from llm_provider import generate_doc_for_file
from pathlib import Path

def run_cmd(cmd, cwd=None):
    print("RUN:", cmd)
    subprocess.run(cmd, shell=True, check=True, cwd=cwd)

def clone_repo_via_token(repo_full_name, token, target_dir):
    # clone using token in URL - token as username 'x-access-token' works for GitHub
    url = f"https://x-access-token:{token}@github.com/{repo_full_name}.git"
    run_cmd(f"git clone --depth 1 {url} {target_dir}")

def handle_push_event(payload):
    # parse payload
    repo = payload.get("repository", {})
    repo_full = repo.get("full_name")  # "org/name"
    installation = payload.get("installation", {})
    installation_id = installation.get("id")
    changed_files = set()
    # get list of changed files from commits
    for commit in payload.get("commits", []):
        changed_files.update(commit.get("added", []))
        changed_files.update(commit.get("modified", []))

    if not changed_files:
        print("No changed files in push, skipping.")
        return

    print("Changed files in push:", sorted(list(changed_files)))

    # get token for this installation
    token = get_installation_token(installation_id)

    tmpdir = tempfile.mkdtemp(prefix="docai_")
    try:
        clone_repo_via_token(repo_full, token, tmpdir)

        docs_dir = Path(tmpdir) / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)

        supported_exts = [".py", ".js", ".ts", ".go", ".java", ".rs", ".cpp", ".c"]
        generated_files = []
        considered_files = []
        for f in changed_files:
            # only handle relevant extensions
            if any(f.endswith(ext) for ext in supported_exts):
                abs_path = Path(tmpdir) / f
                if not abs_path.exists(): 
                    print("file missing:", f); continue
                with open(abs_path, "r", encoding="utf-8", errors="ignore") as fh:
                    code = fh.read()
                md = generate_doc_for_file(f, code)
                target = docs_dir / (f.replace("/", "__") + ".md")
                target.parent.mkdir(parents=True, exist_ok=True)
                with open(target, "w", encoding="utf-8") as out:
                    out.write(md)
                print("Wrote doc for", f, "->", target)
                generated_files.append(target.name)
                considered_files.append(f)
            else:
                print("Skipping unsupported file (no matching extension):", f)

        # Ensure GitBook Git Sync has an entry point and navigation
        if generated_files:
            # README.md acts as root page
            readme_path = docs_dir / "README.md"
            readme_content = (
                "# Project Docs\n\n"
                "This documentation is generated automatically by DocAI from recent commits.\n\n"
                "See the sidebar for individual module/pages.\n"
            )
            with open(readme_path, "w", encoding="utf-8") as fh:
                fh.write(readme_content)
            # SUMMARY.md builds sidebar in GitBook Git Sync
            summary_path = docs_dir / "SUMMARY.md"
            # Sort for stability
            generated_files.sort()
            lines = ["# Summary\n", "\n", "* [Home](README.md)\n"]
            for name in generated_files:
                title = name.replace("__", "/").replace(".md", "")
                lines.append(f"* [{title}]({name})\n")
            with open(summary_path, "w", encoding="utf-8") as fh:
                fh.writelines(lines)

        if not generated_files:
            print("No supported changed files produced docs. Nothing new to commit under docs/.")

        # commit & push back
        run_cmd("git config user.email 'docai@bots.local' && git config user.name 'docai-bot'", cwd=tmpdir)
        run_cmd("git add docs || true", cwd=tmpdir)
        run_cmd("git commit -m 'chore(docs): auto-generated by DocAI' || echo 'no changes'", cwd=tmpdir)
        run_cmd(f"git push https://x-access-token:{token}@github.com/{repo_full}.git HEAD:main", cwd=tmpdir)
        print("Docs committed and pushed.")
    finally:
        shutil.rmtree(tmpdir)


def rebuild_all_for_repo(repo_full: str, installation_id: int):
    """Generate docs for all supported files in a repository and push to docs/.

    Intended for first-time seeding or manual rebuilds.
    """
    token = get_installation_token(installation_id)
    tmpdir = tempfile.mkdtemp(prefix="docai_full_")
    try:
        clone_repo_via_token(repo_full, token, tmpdir)

        docs_dir = Path(tmpdir) / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)

        supported_exts = [".py", ".js", ".ts", ".go", ".java", ".rs", ".cpp", ".c"]
        generated_files = []

        for path in Path(tmpdir).rglob("*"):
            if path.is_file() and any(str(path).endswith(ext) for ext in supported_exts):
                rel = path.relative_to(tmpdir).as_posix()
                try:
                    with open(path, "r", encoding="utf-8", errors="ignore") as fh:
                        code = fh.read()
                except Exception as e:
                    print("skip unreadable:", rel, e)
                    continue
                md = generate_doc_for_file(rel, code)
                target = docs_dir / (rel.replace("/", "__") + ".md")
                target.parent.mkdir(parents=True, exist_ok=True)
                with open(target, "w", encoding="utf-8") as out:
                    out.write(md)
                print("Wrote doc for", rel, "->", target)
                generated_files.append(target.name)

        if generated_files:
            readme_path = docs_dir / "README.md"
            readme_content = (
                "# Project Docs\n\n"
                "This documentation is generated automatically by DocAI.\n\n"
                "Use the sidebar to navigate pages.\n"
            )
            with open(readme_path, "w", encoding="utf-8") as fh:
                fh.write(readme_content)

            summary_path = docs_dir / "SUMMARY.md"
            generated_files.sort()
            lines = ["# Summary\n", "\n", "* [Home](README.md)\n"]
            for name in generated_files:
                title = name.replace("__", "/").replace(".md", "")
                lines.append(f"* [{title}]({name})\n")
            with open(summary_path, "w", encoding="utf-8") as fh:
                fh.writelines(lines)

        run_cmd("git config user.email 'docai@bots.local' && git config user.name 'docai-bot'", cwd=tmpdir)
        run_cmd("git add docs || true", cwd=tmpdir)
        run_cmd("git commit -m 'docs: full rebuild by DocAI' || echo 'no changes'", cwd=tmpdir)
        run_cmd(f"git push https://x-access-token:{token}@github.com/{repo_full}.git HEAD:main", cwd=tmpdir)
        print("Full docs committed and pushed.")
    finally:
        shutil.rmtree(tmpdir)