# processor.py
import os, subprocess, tempfile, shutil
from github_app import get_installation_token
from llm_provider import generate_doc_for_file
from pathlib import Path

def run_cmd(cmd, cwd=None):
    print("RUN:", cmd)
    subprocess.run(cmd, shell=True, check=True, cwd=cwd)

def clone_repo_via_token(repo_full_name, token, target_dir):
    # clone using token in URL - token as username 'x-access-token' works for GitHub
    url = f"https://x-access-token:{token}@github.com/{repo_full_name}.git"
    run_cmd(f"git clone --depth 1 {url} {target_dir}")

def handle_push_event(payload):
    # parse payload
    repo = payload.get("repository", {})
    repo_full = repo.get("full_name")  # "org/name"
    installation = payload.get("installation", {})
    installation_id = installation.get("id")
    changed_files = set()
    # get list of changed files from commits
    for commit in payload.get("commits", []):
        changed_files.update(commit.get("added", []))
        changed_files.update(commit.get("modified", []))

    if not changed_files:
        print("No changed files in push, skipping.")
        return

    # get token for this installation
    token = get_installation_token(installation_id)

    tmpdir = tempfile.mkdtemp(prefix="docai_")
    try:
        clone_repo_via_token(repo_full, token, tmpdir)

        docs_dir = Path(tmpdir) / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)

        for f in changed_files:
            # only handle relevant extensions
            if any(f.endswith(ext) for ext in [".py", ".js", ".ts", ".go", ".java", ".rs", ".cpp", ".c"]):
                abs_path = Path(tmpdir) / f
                if not abs_path.exists(): 
                    print("file missing:", f); continue
                with open(abs_path, "r", encoding="utf-8", errors="ignore") as fh:
                    code = fh.read()
                md = generate_doc_for_file(f, code)
                target = docs_dir / (f.replace("/", "__") + ".md")
                target.parent.mkdir(parents=True, exist_ok=True)
                with open(target, "w", encoding="utf-8") as out:
                    out.write(md)
                print("Wrote doc for", f, "->", target)

        # commit & push back
        run_cmd("git config user.email 'docai@bots.local' && git config user.name 'docai-bot'", cwd=tmpdir)
        run_cmd("git add docs || true", cwd=tmpdir)
        run_cmd("git commit -m 'chore(docs): auto-generated by DocAI' || echo 'no changes'", cwd=tmpdir)
        run_cmd(f"git push https://x-access-token:{token}@github.com/{repo_full}.git HEAD:main", cwd=tmpdir)
        print("Docs committed and pushed.")
    finally:
        shutil.rmtree(tmpdir)